services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-telegram-bot
        container_name: laravel-app
        ports:
            - "9100:9000"
        volumes:
            - .:/var/www
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        container_name: nginx-server
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: monitor-bot
            MYSQL_USER: roman-ta
            MYSQL_PASSWORD: vortexq16
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
