<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ChildCategoriesModel extends Model
{
    protected $table = 'child_categories';
    protected $fillable = [
        'parent_id',
        'child_name',
        'parent_icon',
        'url',
        'created_at',
        'updated_at',
    ];


    public function changeIcons()
    {
        $res = [];
        foreach ($this->categories as $key => &$item) {
            $emojiOnly = preg_replace('/[^\p{So}\p{Sk}]/u', '', $item);
            $res[$key] = $emojiOnly;
        }

        $childs = self::all()->toArray();
        foreach ($childs as $child) {
            if(isset($res[$child['url']])) {
                self::where('id', $child['id'])->update(['parent_icon' => $res[$child['url']]]);
            }
        }

    }


    public $categories = [
        'real-estate/real-estate-for-sale' => '🏠',
        'real-estate/real-estate-for-sale/apartments-for-sale' => '🏡',
        'real-estate/real-estate-for-sale/houses-for-sale' => '🏘️',
        'real-estate/real-estate-for-sale/premises-for-sale' => '🏢 Продажа нежилых помещений',
        'real-estate/real-estate-for-sale/plots-for-sale' => '🌳 Продажа земельных участков',
        'real-estate/real-estate-for-rent' => '🏠 Аренда',
        'real-estate/real-estate-for-rent/apartments-for-rent' => '🏡 Аренда квартир, комнат',
        'real-estate/real-estate-for-rent/houses-for-rent' => '🏘️ Аренда домов',
        'real-estate/real-estate-for-rent/premises-for-rent' => '🏢 Аренда нежилых помещений',
        'real-estate/real-estate-for-rent/plots-for-rent' => '🌳 Аренда земельных участков',
        'real-estate/exchange' => '🔄 Обмен',
        'real-estate/buy-and-rent' => '🛒 Куплю, возьму в аренду',
        'real-estate/real-estate-services' => '🧰 Риэлторские услуги',
        'real-estate/real-estate-abroad' => '✈️ Недвижимость за рубежом',
        'odds-and-ends-exchange-and-buy/temp-other-categories' => '📦 Прочее',
        'confiscated-property/confiscation-transport/confiscation-cars' => '🚗 Легковые автомобили',
        'transport/automotive-parts' => '🛠️ Автокомплектующие',
        'transport/automotive-parts/used-parts' => '⚙️ Разборка авто',
        'transport/automotive-parts/suspension-drive-transmission' => '🔧 Подвеска, привод, трансмиссия',
        'transport/automotive-parts/engine-components' => '🛢️ Двигатель - системы и компоненты',
        'transport/automotive-parts/car-body' => '🛞 Детали кузова',
        'transport/automotive-parts/tires' => '🛞 Шины',
        'transport/automotive-parts/tuning-and-accessories' => '🎛️ Тюнинг, аксессуары',
        'transport/automotive-parts/wheels-and-wheel-caps' => '🛞 Диски и колпаки',
        'transport/automotive-parts/spares-for-maintenance' => '🔩 Запчасти для ТО',
        'transport/automotive-parts/electronics' => '🔌 Электрика - электроника',
        'transport/automotive-parts/oils-and-lubricants' => '🛢️ Масла, смазки',
        'transport/automotive-parts/lights-and-optics' => '💡 Фары, оптика, освещение',
        'transport/automotive-parts/car-glass-and-mirrors' => '🪞 Стекла, зеркала',
        'transport/automotive-parts/conditioners-and-heaters' => '❄️ Кондиционеры, печки',
        'transport/automotive-parts/batteries' => '🔋 Аккумуляторы',
        'transport/automotive-parts/autochemistry' => '🧴 Автохимия',
        'transport/automotive-parts/alarm-systems' => '🔔 Противоугонные системы, сигнализация',
        'transport/transportation' => '🚚 Перевозки',
        'transport/transportation/passenger-transportation' => '🚌 Пассажирские перевозки',
        'transport/transportation/cargo-transportation' => '🚛 Грузоперевозки',
        'transport/transportation/porters' => '🧑‍🔧 Грузчики',
        'transport/transportation/breakdown-truck-services' => '🛠️ Услуги эвакуатора',
        'transport/car-repair' => '🔧 Ремонт и автосервис',
        'transport/trucks' => '🚛 Грузовые автомобили',
        'transport/buses' => '🚌 Автобусы',
        'transport/trailers' => '🚚 Прицепы',
        'transport/motorcycles' => '🏍️ Мото',
        'transport/motorcycles/moto' => '🏍️ Мотоциклы',
        'transport/motorcycles/scooters' => '🛵 Мопеды, скутеры',
        'transport/motorcycles/quads' => '🛴 Квадроциклы',
        'sport-and-leisure/cycle-racing/accessories' => '🚴‍♂️ Аксессуары',
        'transport/motorcycles/wheels' => '🛞 Шины, диски',
        'transport/motorcycles/spare-parts' => '⚙️ Запчасти, комплектующие',
        'transport/special-equipment' => '🚜 Спецтехника',
        'transport/special-equipment/road-construction-machinery' => '🚧 Строительно-дорожная техника',
        'transport/special-equipment/loader' => '🚜 Погрузчики',
        'transport/special-equipment/excavators' => '🏗️ Экскаваторы',
        'transport/car-electronics' => '📻 Аудио, видеосистемы',
        'transport/video-recorder' => '📹 Видеорегистраторы',
        'transport/navigators' => '🧭 Навигаторы',
        'transport/other-types-transport' => '🚛 Другие виды транспорта',
        'confiscated-property/confiscation-transport' => '🚗 Транспорт',
        'confiscated-property/confiscation-transport/confiscation-moto' => '🏍️ Мототранспорт',
        'sport-and-leisure/cycle-racing/bicycles' => '🚲 Велосипеды',
        'confiscated-property/confiscation-transport/confiscation-tires-wheels' => '🛞 Шины, диски и колпаки',
        'confiscated-property/confiscation-transport/confiscation-spares-for-maintenance' => '🔧 Автозапчасти для техобслуживания',
        'confiscated-property/confiscation-transport/confiscation-autochemistry' => '🧴 Химия для авто',
        'weddings-and-celebration/transport-for-parties' => '🎉 Транспорт для торжеств',
        'job/job-offers' => '💼 Работа, вакансии',
        'job/looking-for-job' => '🔍 Ищу работу',
        'job/education' => '🎓 Обучение, курсы, репетиторство',
        'services/bussiness-consulting' => '🛠️ Бизнес и консалтинг',
        'services/health-and-beauty' => '💄 Здоровье и красота',
        'services/health-and-beauty/beauty-salon' => '💇‍♀️ Салон красоты',
        'services/health-and-beauty/medical-services' => '🏥 Медицинские услуги',
        'services/health-and-beauty/massotherapy' => '💆‍♂️ Лечебный массаж',
        'services/health-and-beauty/alternative-medicine' => '🌿 Нетрадиционная медицина',
        'services/health-and-beauty/psychology-consultation' => '🧠 Консультации психолога',
        'services/health-and-beauty/makeup' => '💄 Визаж и макияж',
        'services/health-and-beauty/fashion-and-style' => '👗 Мода и стиль',
        'services/health-and-beauty/hairdressers' => '✂️ Парикмахерские услуги',
        'services/health-and-beauty/cosmetology-services' => '💆‍♀️ Косметологические услуги',
        'services/messages' => '💬 Помощь и консультирование',
        'services/dry-cleaning' => '🧼 Химчистка',
        'services/housework-and-dry-cleaning' => '🧹 Помощь по дому',
        'services/translations' => '🌐 Переводы',
        'services/predictions' => '🔮 Предсказания',
        'services/funeral-services' => '⚰️ Ритуальные услуги',
        'services/advertising-design' => '🎨 Реклама и дизайн',
        'services/other-services' => '🛠️ Другие услуги',
        'construction-and-repair/construction-and-repair/construction-machinery-services' => '🚜 Услуги строительной техники',
        'computers-and-office-equipment/computer-and-internet-services' => '💻 Компьютерные и интернет услуги',
        'plants-and-animals/goods-and-services-for-animals' => '🐶 Товары для животных',
        'plants-and-animals/breeding-services' => '🐰 Услуги и вязка',
        'plants-and-animals/vet-services' => '🐱 Услуги ветеринаров',
        'construction-and-repair/construction-and-repair' => '🏗️ Строительные услуги и ремонт',
        'construction-and-repair/construction-and-repair/walls-and-ceilings-decoration' => '🧱 Отделка стен и потолков',
        'construction-and-repair/construction-and-repair/complex-repairs' => '🔨 Ремонт под ключ',
        'construction-and-repair/construction-and-repair/plumbing' => '🚰 Сантехработы',
        'construction-and-repair/construction-and-repair/electrical-works' => '💡 Электроработы',
        'construction-and-repair/construction-and-repair/wall-insulation' => '❄️ Утепление стен, фасадов',
        'construction-and-repair/construction-and-repair/floor-repairing' => '🛠️ Укладка и ремонт полов',
        'construction-and-repair/construction-and-repair/roofing' => '🏠 Кровельные работы',
        'construction-and-repair/construction-and-repair/drilling-and-logging' => '⛏️ Сверление и вырубка',
        'construction-and-repair/construction-and-repair/doors-installation' => '🚪 Ремонт, установка дверей, окон, замков',
        'construction-and-repair/construction-materials' => '🏗️ Строительные товары и материалы',
        'construction-and-repair/construction-materials/windows-and-doors' => '🪟 Окна и двери',
        'construction-and-repair/construction-materials/metals-and-metal-products' => '🔩 Металлы и изделия',
        'construction-and-repair/construction-materials/materials' => '🧱 Строительные материалы',
        'construction-and-repair/construction-materials/plumbing-heating-and-water-supply' => '🚿 Сантехника, отопление и водоснабжение',
        'construction-and-repair/construction-materials/lumber-and-products' => '🪵 Пиломатериалы и изделия',
        'construction-and-repair/construction-materials/finishing-materials' => '🎨 Отделочные материалы',
        'construction-and-repair/construction-materials/roofing-materials' => '🏘️ Кровельные материалы',
        'construction-and-repair/construction-materials/shutters' => '🪟 Жалюзи и ролеты',
        'construction-and-repair/construction-materials/electric-materials-and-lighting' => '💡 Электрооборудование',
        'construction-and-repair/equipment-housekeeping' => '🧹 Хозяйственные товары',
        'construction-and-repair/equipment-housekeeping/fuel-and-raw-materials' => '⛽ Топливо и сырье',
        'construction-and-repair/equipment-housekeeping/barrels-canisters-containers' => '🛢️ Бочки, канистры, емкости',
        'construction-and-repair/architecture-and-design' => '🏛️ Архитектура и дизайн',
        'construction-and-repair/tools' => '🛠️ Инструменты',
        'construction-and-repair/tools/power-tools' => '🔧 Электроинструменты',
        'construction-and-repair/tools/hand-tools' => '🪚 Ручные инструменты',
        'computers-and-office-equipment/office-equipment/consumables' => '📦 Расходные материалы',
        'furniture-and-interior/furniture' => '🛋 Мебель для дома',
        'furniture-and-interior/furniture/tables-and-chairs' => '🪑 Столы и стулья',
        'furniture-and-interior/furniture/wall-units' => '🧱 Стенки и шкафы',
        'furniture-and-interior/furniture/kitchen-furniture-sets' => '🍽️ Кухни',
        'furniture-and-interior/furniture/bedroom-suites' => '🛏️ Спальни',
        'furniture-and-interior/furniture/lobby-furniture' => '🚪 Прихожие',
        'furniture-and-interior/furniture/upholstered-furniture' => '🛋 Мягкая мебель',
        'furniture-and-interior/furniture-for-country-houses' => '🏡 Дачная и садовая мебель',
        'furniture-and-interior/office-furniture' => '💼 Офисная мебель',
        'furniture-and-interior/furniture-for-restaurants' => '🍴 Мебель для ресторанов, кафе',
        'furniture-and-interior/furniture-for-shops' => '🏪 Мебель для магазинов',
        'furniture-and-interior/furniture-for-children' => '🧸 Детская мебель',
        'furniture-and-interior/all-for-the-comfort' => '🪄 Все для комфорта',
        'furniture-and-interior/all-for-the-comfort/textile-and-bedding' => '🧺 Ткани, постельные принадлежности',
        'furniture-and-interior/all-for-the-comfort/mattresses' => '🛏️ Матрацы',
        'furniture-and-interior/all-for-the-comfort/carpets' => '🧶 Ковры и паласы',
        'furniture-and-interior/all-for-the-comfort/antiques-and-work-of-art' => '🖼️ Антиквариат, предметы искусства, часы',
        'furniture-and-interior/all-for-the-comfort/curtains-and-jalousie' => '🪟 Шторы, жалюзи',
        'furniture-and-interior/all-for-the-comfort/lighting-rigs' => '💡 Светильники, люстры, лампы',
        'furniture-and-interior/all-for-the-comfort/tableware' => '🍽️ Посуда',
        'furniture-and-interior/all-for-the-comfort/household-chemistry' => '🧴 Бытовая химия',
        'furniture-and-interior/furniture-manufacturing-and-repair' => '🔨 Изготовление и ремонт мебели',
        'clothing-footwear-accessories/clothing' => '👚 Одежда',
        'clothing-footwear-accessories/shoes' => '👟 Обувь',
        'clothing-footwear-accessories/clothing/womens-clothing' => '👗 Женская одежда',
        'clothing-footwear-accessories/clothing/mens-clothing' => '🧥 Мужская одежда',
        'clothing-footwear-accessories/clothing/childrens-clothing' => '🧒 Детская одежда',
        'clothing-footwear-accessories/shoes/footwear-women' => '👠 Женская обувь',
        'clothing-footwear-accessories/shoes/footwear-men' => '👞 Мужская обувь',
        'clothing-footwear-accessories/shoes/footwear-children' => '🧒 Детская обувь',
        'clothing-footwear-accessories/working-clothes' => '👷 Спецодежда',
        'clothing-footwear-accessories/accessories-and-haberdashery' => '👜 Аксессуары и галантерея',
        'clothing-footwear-accessories/jewellery-and-watches' => '💍 Бижутерия, ювелирные изделия и часы',
        'clothing-footwear-accessories/footwear-repair' => '👞 Ремонт обуви',
        'clothing-footwear-accessories/clothing-repair' => '🧵 Пошив и ремонт одежды',
        'products-for-children/toys' => '🧸 Игрушки',
        'products-for-children/prams' => '🛒 Коляски',
        'products-for-children/seats' => '🚼 Автокресла',
        'products-for-children/everything-for-school' => '📚 Все для школы',
        'products-for-children/governesses' => '👩‍🍼 Услуги няни, гувернантки',
        'handmade/ornamentation-and-accessories' => '🧶 Украшения и аксессуары',
        'handmade/toys-and-dolls' => '🎎 Игрушки, куклы',
        'handmade/sewing-knitting-embroidery' => '🪡 Шитье, вязание, вышивка',
        'handmade/paintings' => '🎨 Художественная роспись, картины',
        'handmade/postcards-and-paper-products' => '✉️ Открытки и бумажные изделия',
        'handmade/interior-and-dishes' => '🪞 Интерьер и посуда',
        'handmade/handmade-gifts-and-souvenirs' => '🎁 Подарки и сувениры',
        'handmade/woodwork' => '🪵 Изделия из дерева',
        'handmade/soap-and-candles' => '🕯️ Мыло и свечи',
        'computers-and-office-equipment/desktops' => '🖥️ Настольные компьютеры',
        'computers-and-office-equipment/laptops' => '💻 Ноутбуки',
        'computers-and-office-equipment/tablets' => '📱 Планшеты',
        'computers-and-office-equipment/e-books' => '📖 Электронные книги',
        'computers-and-office-equipment/servers' => '🗄️ Серверы',
        'computers-and-office-equipment/game-consoles' => '🎮 Игровые приставки',
        'computers-and-office-equipment/peripherals' => '🧩 Периферийное оборудование',
        'computers-and-office-equipment/peripherals/monitors' => '🖥️ Мониторы',
        'computers-and-office-equipment/peripherals/keyboards-and-mouses' => '⌨️ Клавиатуры и мыши',
        'computers-and-office-equipment/peripherals/webcams' => '📷 Вебкамеры',
        'computers-and-office-equipment/peripherals/speakers' => '🔊 Акустические системы',
        'computers-and-office-equipment/peripherals/cables-and-adapters' => '🔌 Кабели и переходники',
        'computers-and-office-equipment/components/motherboards' => '🧠 Материнские платы',
        'computers-and-office-equipment/components/processors' => '⚙️ Процессоры',
        'computers-and-office-equipment/components/display-adapters' => '🎞️ Видеокарты',
        'computers-and-office-equipment/components/pc-cases' => '📦 Корпуса',
        'computers-and-office-equipment/components/power-units' => '🔋 Блоки питания',
        'computers-and-office-equipment/components/ram' => '🧬 Модули памяти',
        'computers-and-office-equipment/components/storage-devices' => '💾 Накопители (HDD, SSD)',
        'computers-and-office-equipment/components/optical-drives' => '📀 Оптические приводы',
        'computers-and-office-equipment/components/accumulators-and-the-rest' => '🔌 Источники питания, UPS',
        'computers-and-office-equipment/components/network-equipment' => '🌐 Сетевое оборудование',
        'computers-and-office-equipment/office-equipment' => '🖨️ Офисная техника',
        'computers-and-office-equipment/office-equipment/printers' => '🖨️ Принтеры',
        'computers-and-office-equipment/office-equipment/scanners' => '📠 Сканеры',
        'computers-and-office-equipment/office-equipment/copiers' => '🖨️ Копировальные аппараты',
        'computers-and-office-equipment/software' => '💿 Программное обеспечение',
        'computers-and-office-equipment/office-equipment-repair-and-maintenance' => '🛠️ Ремонт и обслуживание оргтехники',
        'audio-photo-video/audio' => '📺',
        'audio-photo-video/audio/players' => '🎵',
        'audio-photo-video/audio/dictaphones' => '🎙️',
        'audio-photo-video/audio/speakers-and-acoustic-systems' => '🔊',
        'audio-photo-video/audio/microphones-headphones' => '🎧',
        'audio-photo-video/audio/home-stereos' => '🎼',
        'audio-photo-video/audio/amplifiers' => '📢',
        'audio-photo-video/video/parts-and-accessories' => '🔧',
        'audio-photo-video/audio/music' => '🎶',
        'audio-photo-video/audio/studio-equipment' => '🎛️',
        'audio-photo-video/video' => '📹',
        'audio-photo-video/video/video-cameras' => '📷',
        'audio-photo-video/video/videotape-recorders-and-cassettes' => '📼',
        'audio-photo-video/video/disc-players' => '💿',
        'audio-photo-video/video/projecting-cameras' => '📽️',
        'audio-photo-video/video/discs-and-films' => '🎞️',
        'audio-photo-video/photo' => '📸',
        'audio-photo-video/photo/digital-cameras' => '📱',
        'audio-photo-video/photo/film-cameras' => '🎥',
        'audio-photo-video/photo/flashes-and-lighting-devices' => '💡',
        'audio-photo-video/photo/tripods-and-mounts' => '🦵',
        'audio-photo-video/photo/equipment-and-accessories' => '🔩',
        'audio-photo-video/tv' => '📺',
        'audio-photo-video/tv/tv-sets' => '🖥️',
        'audio-photo-video/tv/home-cinemas' => '🏠',
        'audio-photo-video/tv/antennas' => '📡',
        'audio-photo-video/optics' => '🔭',
        'audio-photo-video/optics/lenses' => '👓',
        'audio-photo-video/optics/light-filters' => '🌈',
        'audio-photo-video/optics/binoculars-and-spyglasses' => '🔍',
        'audio-photo-video/optics/telescopes-microscopes' => '🧬',
        'audio-photo-video/lighting-and-phonics' => '💡',
        'audio-photo-video/lighting-and-phonics/sound-equipment' => '🎚️',
        'audio-photo-video/lighting-and-phonics/lighting-equipment-and-special-effects' => '✨',
        'audio-photo-video/lighting-and-phonics/recording' => '🎙️',
        'audio-photo-video/repair-and-service' => '🔧',
        'audio-photo-video/professional-photo-and-video' => '🎬',
        'audio-photo-video/photo-and-video-processing-montage' => '🖌️',
        'confiscated-property/confiscation-phones-and-communications' => '📱',
        'phones-and-communications/mobile-phones' => '📞',
        'phones-and-communications/parts-for-phones' => '🔩',
        'phones-and-communications/gsm-modems' => '📡',
        'phones-and-communications/numbers-and-tickets' => '📇',
        'phones-and-communications/radiophones-and-radiostations' => '📻',
        'phones-and-communications/faxes' => '📠',
        'phones-and-communications/fixed-phones' => '☎️',
        'phones-and-communications/phone-service-and-repair' => '🔧',
        'household-products/household-appliances' => '🧺',
        'household-products/household-appliances/refrigerators' => '❄️',
        'household-products/household-appliances/freezers' => '🧊',
        'household-products/household-appliances/kitchen-stoves' => '🔥',
        'household-products/household-appliances/small-kitchen-equipment' => '🍳',
        'household-products/household-appliances/dishwasher' => '🧼',
        'household-products/vacuum-cleaners' => '🧹',
        'household-products/washers' => '🧴',
        'household-products/stitching-and-knitting-machines' => '🧵',
        'household-products/small-things' => '🔌',
        'household-products/repair-of-household-appliances' => '🔧',
        'household-products/air-conditioners-fans' => '🌬️',
        'household-products/heaters-water-heaters' => '♨️',
        'industrial-and-commercial-equipment/industrial-equipment' => '⚙️',
        'industrial-and-commercial-equipment/shop-equipment' => '🏪',
        'industrial-and-commercial-equipment/sewing-and-knitting-equipment' => '🧶',
        'industrial-and-commercial-equipment/instrumentation-and-tooling' => '🔨',
        'industrial-and-commercial-equipment/security-and-safety' => '🛡️',
        'industrial-and-commercial-equipment/security-and-safety/door-intercommunication-systems-and-combination-locks' => '🔐',
        'industrial-and-commercial-equipment/security-and-safety/monitoring-systems-and-protection' => '🎥',
        'industrial-and-commercial-equipment/security-and-safety/security-and-detectives' => '🕵️‍♂️',
        'sport-and-leisure/relax-and-travel' => '🏕',
        'sport-and-leisure/sporting-accessories' => '🏋️',
        'sport-and-leisure/sporting-accessories/training-devices' => '🏃‍♂️',
        'sport-and-leisure/sporting-accessories/equipment-and-inventory' => '🎽',
        'sport-and-leisure/sporting-accessories/sports-clothing-and-footwear' => '👟',
        'sport-and-leisure/sporting-accessories/sports-nutrition' => '🥤',
        'sport-and-leisure/sporting-accessories/swimming-pools' => '🏊',
        'sport-and-leisure/sports-clubs-and-sections' => '🤸',
        'sport-and-leisure/sports-clubs-and-sections/martial-arts' => '🥋',
        'sport-and-leisure/sports-clubs-and-sections/yoga-and-fitness' => '🧘',
        'sport-and-leisure/sports-clubs-and-sections/dancing' => '💃',
        'sport-and-leisure/sports-clubs-and-sections/team-sports' => '🤾',
        'sport-and-leisure/sports-clubs-and-sections/exercise-rooms' => '🏋️‍♀️',
        'sport-and-leisure/sports-clubs-and-sections/tennis' => '🎾',
        'sport-and-leisure/cycle-racing' => '🚴',
        'sport-and-leisure/extreme-sports' => '🏂',
        'sport-and-leisure/hunting-and-fishing' => '🎣',
        'sport-and-leisure/entertainment-and-hobby' => '🎲',
        'sport-and-leisure/sauna-and-bath' => '🛁',
        'plants-and-animals/dogs' => '🐶',
        'plants-and-animals/cats' => '🐱',
        'plants-and-animals/rodents' => '🐹',
        'plants-and-animals/birds' => '🐦',
        'plants-and-animals/fishes' => '🐟',
        'plants-and-animals/other-animals' => '🐾',
        'plants-and-animals/house-plants' => '🌿',
        'plants-and-animals/fertilizer-equipment-supplies' => '🧴',
        'agribusiness/fertilizers' => '🌾',
        'agribusiness/farming-machines' => '🚜',
        'agribusiness/farming-machines/mechanisms' => '⚙️',
        'agribusiness/farming-machines/equipment-inventory' => '🛠️',
        'agribusiness/farm-implements' => '🌱',
        'agribusiness/livestock' => '🐄',
        'agribusiness/feedstuff' => '🌾',
        'agribusiness/farm-work' => '👩‍🌾',
        'agribusiness/seed' => '🌰',
        'agribusiness/trees-and-shrubs' => '🌳',
        'agribusiness/fresh-fruits-and-vegetables' => '🍎',
        'dating/looking-for-friends' => '❤️',
        'dating/looking-for-partners' => '💘',
        'dating/marriage-posts' => '💍',
        'weddings-and-celebration/halls-for-festivities' => '🎉',
        'weddings-and-celebration/music-and-masters-of-ceremonies' => '🎤',
        'weddings-and-celebration/for-rent' => '🏠',
        'weddings-and-celebration/planning-and-decorating-festivities' => '🎨',
        'weddings-and-celebration/carnival-costumes-and-accessories' => '🎭',
        'weddings-and-celebration/other' => '🎈',
        'hobbies-and-entertainment/music' => '🎼',
        'hobbies-and-entertainment/board-games' => '🎲',
        'hobbies-and-entertainment/cards' => '🃏',
        'hobbies-and-entertainment/children-s-toys' => '🧸',
        'hobbies-and-entertainment/other' => '🎯',
    ];


}
